sometimes main can exit 2
FAIL	github.com/gotestyourself/gotestyourself/testjson/internal/badmain	0.000s
ok  	github.com/gotestyourself/gotestyourself/testjson/internal/good	(cached)
this is a Print
--- FAIL: TestFailed (0.00s)
	stub_test.go:34: this failed
this is stderr
this is stderr
--- FAIL: TestFailedWithStderr (0.00s)
	stub_test.go:43: also failed
--- FAIL: TestNestedWithFailure (0.00s)
    --- FAIL: TestNestedWithFailure/c (0.00s)
    	stub_test.go:65: failed
FAIL
FAIL	github.com/gotestyourself/gotestyourself/testjson/internal/stub	0.011s
